### ISSUE TITLE
Handle redefining of predefined types

### ISSUE THREAD

**Issue by jcklie** [dkpro/dkpro-cassis#41]
Some CAS handling frameworks redefine predefined types like `DocumentAnnotation`. In order to not throw the error that the type already exists, it would be nice to check whether they are exactly the same type and then ignore it. Also, it would be nice to also redefine this type on export again to keep the type system as is.

**Comment by reckart** [comment]
Among the type provided by the UIMA framework, `DocumentAnnotation` has a special role because it is not really built-in. It comes with the framework but is defined in a separate JAR which needs to be included specifically. Users can also not use the official JAR but use their own. Additionally, it is not feature or inheritance final, which means it can be subject to extension via type system merging.

So if the UIMA framework detects two different yet compatible definitions of a type, these definitions are merged. There is no problem with "type exists" and no problem with "redefinition" as long as the definitions do not contradict each other.

**Comment by jcklie** [comment]
I will handle the idiosyncrasies of `DocumentAnnotation` in #12 . For this PR, I just wanted to make sure that we can read type systems with and without its definition.
