### ISSUE TITLE
Creating cas without typesystem shares the default typesystem

### ISSUE THREAD

**Issue by jcklie** [dkpro/dkpro-cassis#67]
**Describe the bug**
Creating cas without typesystem shares the default typesystem

**To Reproduce**
1. Create two casses with `cas1 = Cas(); cas2 = Cas()`
2. Add a new type to both
3. Error is thrown due to duplicate type

**Expected behavior**
Casses both have different type system

**Comment by jcklie** [comment]
```
class Cas:
    """A CAS object is a container for text (sofa) and annotations"""

    def __init__(self, typesystem: TypeSystem = TypeSystem()):
        self._typesystem = typesystem
```

In Python, the default parameter is shared globally. That is bad because it is mutable.

**Comment by jcklie** [comment]
The default type system is empty except predefined UIMA types

**Comment by reckart** [comment]
thanks :)

**Comment by reckart** [comment]
Does Cassis allow to change the type system after a CAS has been created? If yes, you might care to advertise this somewhere because one of the things people tend find limiting about the Java implementation is that the the type system cannot be changed after the CAS has been initialized, in particular no types can be added and no features can be added to types.

**Comment by jcklie** [comment]
Same mistake in `load_cas_from_xmi`
