### ISSUE TITLE
Add function to select first covering annotation

### ISSUE THREAD

**Issue by jcklie** [dkpro/dkpro-cassis#68]
**Is your feature request related to a problem? Please describe.**
It is annoying to get the first covering annotation e.g. of a sentence.

**Describe the solution you'd like**
Add function to select first covering annotation

**Comment by reckart** [comment]
What is the "first covering annotation"?

**Comment by jcklie** [comment]
Right now, select covering returns an iterator. In Python it is really hard to check whether there is something behind this iterator. So I wand select_covering_first or so e.g. when a sentence is completely covered by an annotation.

**Comment by reckart** [comment]
Ok, I see that Python has no `hasNext()` method, but you check whether the `next()` method throws `StopIteration`. Of course calling `next()` consumes an item from the iterator - but I guess you could return an iterable object from `select` instead of an iterator (i.e. some class which implements `iter()`?

**Comment by reckart** [comment]
In Java UIMAv3, you would write something like `cas.select(MyType).limit(1)` which conveniently returns an `Iterable` object so it can be used in extended loops.

**Comment by jcklie** [comment]
We return lists now instead of iterators, so this problem should be solved by using result[0]
